default: &default
  host: 127.0.0.1
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: shinshire
  password: <%= ENV['SHIN_PG_PASSWORD'] %> 

development:
  <<: *default
  database: my_db_dev

test:
  <<: *default
  database: my_db_test

production:
  <<: *default
  database: my_db_prod
